set_inicial = {11, 12, 13, 14}
print("Conteúdo inicial do set:", set_inicial)
set_inicial.add(15)
print("Set após adicionar o elemento 15:", set_inicial)
set_inicial.update([1, 2, 3, 4, 5])
print("Set após atualizar com os elementos 1, 2, 3, 4, 5:", set_inicial)
set_inicial.discard(13)
print("Set após remover o elemento 13:", set_inicial)
novo_set = set([20, 21, 23, 1, 2])
print("Conteúdo do novo set:", novo_set)
uniao_sets = set_inicial.union(novo_set)
print("União entre os dois sets:", uniao_sets)
intersecao_sets = set_inicial.intersection(novo_set)
print("Interseção entre os dois sets:", intersecao_sets)
diferenca_sets = set_inicial.difference(novo_set)
print("Diferença entre 'set_inicial' e 'novo_set':", diferenca_sets)
diferenca_simetrica_sets = set_inicial.symmetric_difference(novo_set)
print("Diferença simétrica entre os dois sets:", diferenca_simetrica_sets)
